Amazon:
  0: ['Amazon', 'Instant', 'Video']
  1: ['Apps', 'Android']
  2: ['Automotive']
  3: ['Baby']
  4: ['Beauty']
  5: ['Books']
  6: ['CDs', 'Vinyl']
  7: ['Cell', 'Phones', 'Accessories']
  8: ['Clothing', 'Shoes', 'Jewelry']
  9: ['Digital', 'Music']
  10: ['Electronics']
  11: ['Grocery', 'Food']
  12: ['Health', 'Personal', 'Care']
  13: ['Home', 'Kitchen']
  14: ['book', 'Store']
  15: ['Movies', 'TV']
  16: ['Musical', 'Instruments']
  17: ['Office', 'Products']
  18: ['Patio', 'Lawn', 'Garden']
  19: ['Pet', 'Supplies']
  20: ['Sports', 'Outdoors']
  21: ['Tools', 'Home', 'Improvement']
  22: ['Toys', 'Games']
  23: ['Video', 'Games']

News20:
  # 0,2,3,8,9,15
  0: ['politics', "Middle Eastern wars"]
  1: ["science", "space"]
  2: ['sale', 'business marketing']
  3: ['politics', 'others']
  4: ['computer', 'graphics']
  5: ['science', 'crypt', 'encryption']
  6: ['computer', 'windows', 'system']
  7: ['computer', 'os', 'ms', 'windows', 'system']
  8: ['politics', 'guns']
  9: ['religion']
  10: ['Recreation', 'auto', 'Automobiles', 'car']
  11: ['science', 'medicine', 'treatment']
  12: ['computer', 'mac', 'hardware', 'system']
  13: ['science', 'electronics', 'Circuits']
  14: ['Recreation', 'sports', 'hockey']
  15: ['skepticism', 'Atheist']
  16: ['Recreation', 'motorcycles']
  17: ['computer', 'system', 'ibm', 'pc', 'hardware']
  18: ['Recreation', 'sports', 'baseball']
  19: ['Society', 'religion', 'christian', 'Christianity']

Reuters:
  0: ["acquisitions"]
  1: ["aluminum"]
  2: ["bop"]
  3: ["cocoa"]
  4: ["coffee"]
  5: ["copper"]
  6: ["cotton"]
  7: ["cpi"]
  8: ["crude"]
  9: ["earn"]
  10: ["gross national product"]
  11: ["gold"]
  12: ["grain"]
  13: ["interest"]
  14: ["industrial production index"]
  15: ["iron steel"]
  16: ["jobs"]
  17: ["livestock"]
  18: ["money fx"]
  19: ["money supply"]
  20: ["nat gas"]
  21: ["orange"]
  22: ["reserves"]
  23: ["retail"]
  24: ["rubber"]
  25: ["ship"]
  26: ["sugar"]
  27: ["tin"]
  28: ["trade"]
  29: ["oil"]
  30: ["Wholesale Price Index"]

HuffPost:
  0: ["POLITICS"]
  1: ["WELLNESS"]
  2: ["ENTERTAINMENT"]
  3: ["TRAVEL TRIP"]
  4: ["STYLE BEAUTY"]
  5: ["PARENTING"]
  6: ["HEALTHY LIVING"]
  7: ["QUEER VOICES"]
  8: ["FOOD DRINK"]
  9: ["BUSINESS COMPANY"]
  10: ["COMEDY"]
  11: ["SPORTS"]
  12: ["BLACK VOICES"]
  13: ["HOME LIVING"]
  14: ["PARENTS"]
  15: ["WORLD POST"]
  16: ["WEDDINGS"]
  17: ["WOMEN"]
  18: ["IMPACT"]
  19: ["DIVORCE"]
  20: ["CRIME"]
  21: ["MEDIA"]
  22: ["WEIRD NEWS"]
  23: ["GREEN"]
  24: ["WORLD POST"]
  25: ["RELIGION belief"]
  26: ["STYLE fashion"]
  27: ["SCIENCE"]
  28: ["WORLD NEWS"]
  29: ["TASTE"]
  30: ["TECH TECHNOLOGY"]
  31: ["MONEY"]
  32: ["ARTS ART"]
  33: ["FIFTY"]
  34: ["GOOD NEWS"]
  35: ["ARTS CULTURE"]
  36: ["ENVIRONMENT"]
  37: ["COLLEGE UNIVERSITY SCHOOL"]
  38: ["LATINO VOICES"]
  39: ["CULTURE ARTS"]
  40: ["EDUCATION"]

Liu54:
  0: ['coffee']
  1: ['music']
  2: ['unusual', "abnormal"]
  3: ['radio']
  4: ['neutral']
  5: ['hue', 'light change']
  6: ["fact"]
  7: ["create", "add"]
  8: ['movies', "movie"]
  9: ['repeat']
  10: ['confirm']
  11: ['stock']
  12: ['order']
  13: ['convert']
  14: ['volume', 'down']
  15: ['locations', "location"]
  16: ['add contact']
  17: ['joke', "fun"]
  18: ['post', "mail"]
  19: ['traffic', "transport"]
  20: ['events', "event"]
  21: ['settings', "setting"]
  22: ["dislike"]
  23: ['podcast', "digital audio"]
  24: ['query']
  25: ['volume', 'mute']
  26: ['electronics', 'off']
  27: ['deny']
  28: ['hue', 'light up']
  29: ['game']
  30: ['greet']
  31: ['set']
  32: ['volume', 'up']
  33: ['hue', 'light off']
  34: ['definition define']
  35: ['taxi']
  36: ['currency']
  37: ['hue', 'light dim']
  38: ['confirm']
  39: ['command stop']
  40: ['send email']
  41: ['remote', 'control']
  42: ['cleaning clean']
  43: ['remove']
  44: ['hue', 'light on']
  45: ['ticket']
  46: ['volume']
  47: ['audio book']
  48: ['query']
  49: ['recipe menu']
  50: ['math']
  51: ['praise']
  52: ['explain illustrate']
  53: ['likeness similarity resemblance']

Hwu64:
  0: ['explain']
  1: ['recommendation', 'events']
  2: ['order']
  3: ['alarm', 'query']
  4: ['query']
  5: ['electronics']
  6: ['weather', 'query']
  7: ['social', 'post']
  8: ['play', 'radio']
  9: ['unusual', "abnormal"]
  10: ['play', 'audio']
  11: ['hue light off']
  12: ['transport transportation', 'query']
  13: ['play', 'music']
  14: ['news', 'query']
  15: ['transport', 'taxi']
  16: ['cooking', 'recipe']
  17: ['lists', 'query']
  18: ['fact reality']
  19: ['email', "send"]
  20: ['joke']
  21: ['audio', 'volume down']
  22: ['repeat']
  23: ['recommendation recommend', 'locations location']
  24: ['music', 'likeness']
  25: ['music', 'settings']
  26: ['email', 'query']
  27: ['hue light on']
  28: ['audio', 'volume up']
  29: ['hue light change']
  30: ['cleaning clean']
  31: ['music', 'query']
  32: ['confirm']
  33: ['alarm', 'set']
  34: ['chat off']
  35: ['transport transportation', 'traffic']
  36: ['currency']
  37: ['command stop']
  38: ['hue light up']
  39: ['coffee']
  40: ['praise']
  41: ['date time', 'query']
  42: ['definition define']
  43: ['calendar', 'set']
  44: ['ask', 'math']
  45: ['confirmation', 'confirm']
  46: ['deny']
  47: ['stock', "savings", "question"]
  48: ['calendar', 'remove']
  49: ['lists', 'remove']
  50: ['recommendation recommend', 'movies movie']
  51: ['email', 'query contact']
  52: ['hue light dim']
  53: ['play', 'podcast']
  54: ['lists', 'create add']
  55: ['transport', 'ticket']
  56: ['email', 'add contact']
  57: ['audio', 'volume mute']
  58: ['play', 'game']
  59: ['neutral']
  60: ['calendar', 'query']
  61: ['alarm', 'remove']
  62: ['social', 'query']
  63: ['datetime', 'convert']